FROM node:18.10
WORKDIR /app
COPY package*.json ./
COPY tsconfig*.json ./
RUN npm install
COPY . .
ARG API_URI
ENV API_URI ${API_URI:-http://localhost:5000/graphql/}

EXPOSE 5001
USER node
CMD "npm" "run" "dev"