# Generated by Django 3.2.16 on 2022-10-22 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='link',
            new_name='original_link',
        ),
    ]
